### ISSUE TITLE
No guide how to start the app

### ISSUE THREAD

**Issue by XDavidT** [AbirHasan2005/Watermark-Bot#1]
There is no guide with commands (installing all the pip packages), and no reason why need to provide all this configs and not only bot API.
'start' isn't starting this python program, but I'm not sure I'm running the right one.
Please provide more information.

**Comment by MrBotDeveloper** [comment]
Why needed the steps just simply deploy on heroku .....

**Comment by AbirHasan2005** [comment]
Now Done!
Thanks to @MrBotDeveloper for #2 Pull Request.
